In [1]:
import pandas as pd
import numpy as np
import matplotlib

from matplotlib import pyplot as plt
import seaborn as sns

temp_reader = pd.read_csv("pollution_us_2000_2016.csv", chunksize=1000)
airpollution_df = pd.concat(temp_reader, ignore_index=True)

In [2]:
airpollution_df.head()

,Unnamed: 0,State Code,County Code,Site Num,Address,State,County,City,Date Local,NO2 Units,...,SO2 Units,SO2 Mean,SO2 1st Max Value,SO2 1st Max Hour,SO2 AQI,CO Units,CO Mean,CO 1st Max Value,CO 1st Max Hour,CO AQI
0,0,4,13,3002,1645 E ROOSEVELT ST-CENTRAL PHOENIX STN,Arizona,Maricopa,Phoenix,2000-01-01,Parts per billion,...,Parts per billion,3.000000,9.0,21,13.0,Parts per million,1.145833,4.2,21,NaN
1,1,4,13,3002,1645 E ROOSEVELT ST-CENTRAL PHOENIX STN,Arizona,Maricopa,Phoenix,2000-01-01,Parts per billion,...,Parts per billion,3.000000,9.0,21,13.0,Parts per million,0.878947,2.2,23,25.0
2,2,4,13,3002,1645 E ROOSEVELT ST-CENTRAL PHOENIX STN,Arizona,Maricopa,Phoenix,2000-01-01,Parts per billion,...,Parts per billion,2.975000,6.6,23,NaN,Parts per million,1.145833,4.2,21,NaN
3,3,4,13,3002,1645 E ROOSEVELT ST-CENTRAL PHOENIX STN,Arizona,Maricopa,Phoenix,2000-01-01,Parts per billion,...,Parts per billion,2.975000,6.6,23,NaN,Parts per million,0.878947,2.2,23,25.0
4,4,4,13,3002,1645 E ROOSEVELT ST-CENTRAL PHOENIX STN,Arizona,Maricopa,Phoenix,2000-01-02,Parts per billion,...,Parts per billion,1.958333,3.0,22,4.0,Parts per million,0.850000,1.6,23,NaN

In [7]:
#list all columns
airpollution_df.columns

Index([u'Unnamed: 0', u'State Code', u'County Code', u'Site Num', u'Address',
       u'State', u'County', u'City', u'Date Local', u'NO2 Units', u'NO2 Mean',
       u'NO2 1st Max Value', u'NO2 1st Max Hour', u'NO2 AQI', u'O3 Units',
       u'O3 Mean', u'O3 1st Max Value', u'O3 1st Max Hour', u'O3 AQI',
       u'SO2 Units', u'SO2 Mean', u'SO2 1st Max Value', u'SO2 1st Max Hour',
       u'SO2 AQI', u'CO Units', u'CO Mean', u'CO 1st Max Value',
       u'CO 1st Max Hour', u'CO AQI'],
      dtype='object')

In [18]:
ca_airpollution_df=airpollution_df[airpollution_df['State']=="California"]
del ca_airpollution_df['Unnamed: 0']
ca_airpollution_df.head()

,State Code,County Code,Site Num,Address,State,County,City,Date Local,NO2 Units,NO2 Mean,...,SO2 Units,SO2 Mean,SO2 1st Max Value,SO2 1st Max Hour,SO2 AQI,CO Units,CO Mean,CO 1st Max Value,CO 1st Max Hour,CO AQI
3516,6,13,2,2956-A TREAT BOULEVARD,California,Contra Costa,Concord,2000-01-01,Parts per billion,14.782609,...,Parts per billion,0.636364,2.0,9,3.0,Parts per million,0.556522,1.3,4,NaN
3517,6,13,2,2956-A TREAT BOULEVARD,California,Contra Costa,Concord,2000-01-01,Parts per billion,14.782609,...,Parts per billion,0.636364,2.0,9,3.0,Parts per million,0.572222,0.8,6,9.0
3518,6,13,2,2956-A TREAT BOULEVARD,California,Contra Costa,Concord,2000-01-01,Parts per billion,14.782609,...,Parts per billion,0.600000,2.0,11,NaN,Parts per million,0.556522,1.3,4,NaN
3519,6,13,2,2956-A TREAT BOULEVARD,California,Contra Costa,Concord,2000-01-01,Parts per billion,14.782609,...,Parts per billion,0.600000,2.0,11,NaN,Parts per million,0.572222,0.8,6,9.0
3520,6,13,2,2956-A TREAT BOULEVARD,California,Contra Costa,Concord,2000-01-02,Parts per billion,16.043478,...,Parts per billion,1.000000,2.0,5,3.0,Parts per million,0.578261,1.1,21,NaN